### ISSUE TITLE
Field not rendered in detail

### ISSUE THREAD

**Issue by hexlay** [emilianotisato/nova-tinymce#75]
Hello, field is showing html elements and is not rendered. Only workaround i found is to define for example 2 descriptions and show TinyMCE one in only forms and other Text (asHtml) as showcase... However it would be amazing if it had asHtml or it rendered it automatically.

Thanks !

**Comment by daanadriaan** [comment]
Fixed in https://github.com/emilianotisato/nova-tinymce/pull/78/

**Comment by jcsoriano** [comment]
Just bumping this up and hoping #78 can be merged :)

**Comment by Specialistinwebsites** [comment]
Has this been reverted? I don't see this in 2.0.0. Applying `'asHtml' => true` before rule 27 in NovaTinyMCE.php should fix this issue. You could also pass it as an option and make "ashtml" available in nova-tinymce.php. Looking forward to seeing this fixed in 2.0.1.

**Comment by Pondake** [comment]
This issue is still present. Not sure why OP closed the issue.

**Comment by mhtghn** [comment]
For those experiencing this issue, you could for now just add `->withMeta(['asHtml' => true])` to the `NovaTinyMCE` field on your resource
